name: Production Release

on:
  push:
    workflow_dispatch:

jobs:
  publish-alpha:
    name: Publish to PRODUCTION 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        name: Cache Gradle packages
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Get Version
        id: get_build_version
        run: |
          echo "::set-output name=build_version::$(./gradlew -q currentVersion)"
      - name: Publish 
        run: |
          ./gradlew publishPlugin -PexternalVersion=${{ steps.get_build_version.outputs.build_version }} -Pchannel=production
        env:
          HUB_TOKEN: ${{ secrets.HUB_TOKEN }}
